### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [katrinleinweber/oh-my-zsh-youtube-dl-aliases#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

**Comment by katrinleinweber** [comment]
Thank you :-) There is even a neater shortcut for that on GitHub, under `/community/license/new` in the repo.
