### ISSUE TITLE
[oh-my-zsh] plugin 'youtube-dl' not found

### ISSUE THREAD

**Issue by faucetsr** [katrinleinweber/oh-my-zsh-youtube-dl-aliases#2]
Os: Manjaro Linux

Error in shell ZSH + Oh my ZSH:
   [oh-my-zsh] plugin 'youtube-dl' not found
   User@pc~

I follow all the installation steps and I have checked the hidden path /home/user/.oh-my-zsh/custom and the folder 'oh-my-zsh-youtube-dl-aliases' does appear.

How can I solve that?

**Comment by katrinleinweber** [comment]
My bad, I'm sorry. This instruction update should help: https://github.com/katrinleinweber/oh-my-zsh-youtube-dl-aliases/pull/3/files
